#!/bin/bash

# VPN
alias nordup="nordvpn connect Singapore"
alias nordown="nordvpn disconnect"

# Docker
alias dpss='docker ps -a --format "table {{.Names}}\t{{.Image}}\t{{.CreatedAt}}\t{{.Status}}"'
alias dcu="docker compose up"
alias dcdv="docker compose down -v"

# System
alias celar="clear"
alias keyon='sudo brightnessctl -d asus::kbd_backlight s 100%'
alias keyoff='sudo brightnessctl -d asus::kbd_backlight s 0%'

# Python
alias venv="source .venv/bin/activate"
alias genv="source ~/.global/bin/activate"

# Media
alias dlp='yt-dlp -o "%(uploader)s - %(title)s.%(ext)s" --recode-video mp4'

# Misc
alias n8n="docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n"
alias gpt="sgpt --repl temp"
